# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/recognize_ingredients.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/recognize_ingredients.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protos/recognize_ingredients.proto\"2\n!RecognizeIngredientsStreamRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"T\n\x1cRecognizeIngredientsResponse\x12\x34\n\x0bingredients\x18\x01 \x03(\x0b\x32\x1f.RecognizeIngredientsIngredient\"c\n\x1eRecognizeIngredientsIngredient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02\x42+\xaa\x02(IntelliCook.IngredientRecognition.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.recognize_ingredients_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002(IntelliCook.IngredientRecognition.Client'
  _globals['_RECOGNIZEINGREDIENTSSTREAMREQUEST']._serialized_start=38
  _globals['_RECOGNIZEINGREDIENTSSTREAMREQUEST']._serialized_end=88
  _globals['_RECOGNIZEINGREDIENTSRESPONSE']._serialized_start=90
  _globals['_RECOGNIZEINGREDIENTSRESPONSE']._serialized_end=174
  _globals['_RECOGNIZEINGREDIENTSINGREDIENT']._serialized_start=176
  _globals['_RECOGNIZEINGREDIENTSINGREDIENT']._serialized_end=275
# @@protoc_insertion_point(module_scope)
