# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/select_ingredient.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/select_ingredient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/select_ingredient.proto\"Z\n\x1dSelectIngredientStreamRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x01x\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"K\n\x1eSelectIngredientStreamResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_nameB+\xaa\x02(IntelliCook.IngredientRecognition.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.select_ingredient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002(IntelliCook.IngredientRecognition.Client'
  _globals['_SELECTINGREDIENTSTREAMREQUEST']._serialized_start=34
  _globals['_SELECTINGREDIENTSTREAMREQUEST']._serialized_end=124
  _globals['_SELECTINGREDIENTSTREAMRESPONSE']._serialized_start=126
  _globals['_SELECTINGREDIENTSTREAMRESPONSE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
