# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import (
    recognize_ingredients_pb2 as protos_dot_recognize__ingredients__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x1a\"protos/recognize_ingredients.proto2\x81\x01\n\x1cIngredientRecognitionService\x12\x61\n\x1aRecognizeIngredientsStream\x12\".RecognizeIngredientsStreamRequest\x1a\x1d.RecognizeIngredientsResponse(\x01\x42+\xaa\x02(IntelliCook.IngredientRecognition.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002(IntelliCook.IngredientRecognition.Client'
  _globals['_INGREDIENTRECOGNITIONSERVICE']._serialized_start=61
  _globals['_INGREDIENTRECOGNITIONSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
