// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace IntelliCook.IngredientRecognition.Client {
  public static partial class IngredientRecognitionService
  {
    static readonly string __ServiceName = "IngredientRecognitionService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest> __Marshaller_RecognizeIngredientsStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse> __Marshaller_RecognizeIngredientsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse> __Method_RecognizeIngredientsStream = new grpc::Method<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "RecognizeIngredientsStream",
        __Marshaller_RecognizeIngredientsStreamRequest,
        __Marshaller_RecognizeIngredientsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::IntelliCook.IngredientRecognition.Client.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for IngredientRecognitionService</summary>
    public partial class IngredientRecognitionServiceClient : grpc::ClientBase<IngredientRecognitionServiceClient>
    {
      /// <summary>Creates a new client for IngredientRecognitionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngredientRecognitionServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IngredientRecognitionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngredientRecognitionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngredientRecognitionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngredientRecognitionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse> RecognizeIngredientsStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecognizeIngredientsStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsStreamRequest, global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsResponse> RecognizeIngredientsStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_RecognizeIngredientsStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override IngredientRecognitionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IngredientRecognitionServiceClient(configuration);
      }
    }

  }
}
#endregion
