// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IntelliCook.IngredientRecognition.Client {

  /// <summary>Holder for reflection information generated from Protos/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3Mvc2VydmljZS5wcm90bxoicHJvdG9zL3JlY29nbml6ZV9pbmdy",
            "ZWRpZW50cy5wcm90bxoecHJvdG9zL3NlbGVjdF9pbmdyZWRpZW50LnByb3Rv",
            "MuABChxJbmdyZWRpZW50UmVjb2duaXRpb25TZXJ2aWNlEmEKGlJlY29nbml6",
            "ZUluZ3JlZGllbnRzU3RyZWFtEiIuUmVjb2duaXplSW5ncmVkaWVudHNTdHJl",
            "YW1SZXF1ZXN0Gh0uUmVjb2duaXplSW5ncmVkaWVudHNSZXNwb25zZSgBEl0K",
            "FlNlbGVjdEluZ3JlZGllbnRTdHJlYW0SHi5TZWxlY3RJbmdyZWRpZW50U3Ry",
            "ZWFtUmVxdWVzdBofLlNlbGVjdEluZ3JlZGllbnRTdHJlYW1SZXNwb25zZSgB",
            "MAFCK6oCKEludGVsbGlDb29rLkluZ3JlZGllbnRSZWNvZ25pdGlvbi5DbGll",
            "bnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsReflection.Descriptor, global::IntelliCook.IngredientRecognition.Client.SelectIngredientReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
