// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IntelliCook.IngredientRecognition.Client {

  /// <summary>Holder for reflection information generated from Protos/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3Mvc2VydmljZS5wcm90bxoicHJvdG9zL3JlY29nbml6ZV9pbmdy",
            "ZWRpZW50cy5wcm90bzKBAQocSW5ncmVkaWVudFJlY29nbml0aW9uU2Vydmlj",
            "ZRJhChpSZWNvZ25pemVJbmdyZWRpZW50c1N0cmVhbRIiLlJlY29nbml6ZUlu",
            "Z3JlZGllbnRzU3RyZWFtUmVxdWVzdBodLlJlY29nbml6ZUluZ3JlZGllbnRz",
            "UmVzcG9uc2UoAUIrqgIoSW50ZWxsaUNvb2suSW5ncmVkaWVudFJlY29nbml0",
            "aW9uLkNsaWVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IntelliCook.IngredientRecognition.Client.RecognizeIngredientsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
